=== WThomson1905/EmployeeProject/EmployeeProject/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

    "type": "object",
    "properties": {
      "employeeId": {
        "type": "integer"
      },
      "forename": {
        "type": "string"
      },
      "surname": {
        "type": "string"
      },
      "email": {
        "type": "string",
        "format": "email",
        "description": "email description"
      },
      "position": {
        "type": "integer",
        "minimum": 0,
        "maximum": 2
      }
    },
    "required": [
      "employeeId",
      "forename",
      "surname",
      "email",
      "position"
    ]
  


}

=== WThomson1905/EmployeeProject/EmployeeProject/Employees.json
[{"employeeId":1,"forename":"Tom","surname":"Cruise","email":"tc@g.com","position":0},{"employeeId":2,"forename":"Brad","surname":"Pitt","email":"bp@g.com","position":1},{"employeeId":3,"forename":"Bill","surname":"Sandler","email":"bs@g.com","position":0},{"employeeId":4,"forename":"Jack","surname":"Sheppard","email":"js@g.com","position":1},{"employeeId":9,"forename":"William","surname":"Thomson","email":"wt@gmail.com","position":0},{"employeeId":9,"forename":"William","surname":"Thomson","email":"wt@gmail.com","position":0},{"employeeId":6,"forename":"qqq\t","surname":"qqqqq\t","email":"q@g.com\t","position":1},{"employeeId":7,"forename":"qwerty","surname":"asdfg","email":"qa@g.com","position":2},{"employeeId":1231,"forename":"qwe","surname":"qwe","email":"qwe","position":0},{"employeeId":11111,"forename":"11111","surname":"11111","email":"11111","position":1}]
